package:
  name: rnaseqpipeline
  version: 1.0

build:
  number: 0

requirements:
  run:
    - python
    - stringtie >=1.2.3
    - tandemrepeatfinder
    - repeatmodeler
    - blast
    - repeatmasker
    - infernal
    - rfamtoolkit
    - trnascan-se
    - maker >= 2.31.10
    - snap
    - augustus
    - interproscan

about:
  summary: This is a meta-package for the RNAseq pipeline
