package:
  name: tRNAscanSE 
  version: "2.0"

source:
    fn: trnascan-se-2.0.0.tar.gz
    url: http://trna.ucsc.edu/software/trnascan-se-2.0.0.tar.gz
build:
  number: 0

requirements:
    build:
        - {{ compiler('c') }}
    run:
        - infernal
about:
  summary: tRNAscan-SE
