package:
  name: rfamtoolkit 
  version: "1.0"

source:
    fn: rfam-toolkit-master.zip 
    url: https://github.com/jorisvansteenbrugge/rfam-toolkit/archive/master.zip
build:
  number: 2

requirements:
  run:
    - infernal
    - python 
about:
  summary: Rfam-toolkit
